# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class TestStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TestStreamSimple = channel.stream_unary(
        '/test.Test/TestStreamSimple',
        request_serializer=test__pb2.TestRequest.SerializeToString,
        response_deserializer=test__pb2.TestResponse.FromString,
        )
    self.TestSimpleStream = channel.unary_stream(
        '/test.Test/TestSimpleStream',
        request_serializer=test__pb2.TestRequest.SerializeToString,
        response_deserializer=test__pb2.TestResponse.FromString,
        )
    self.TestSimpleSimple = channel.unary_unary(
        '/test.Test/TestSimpleSimple',
        request_serializer=test__pb2.TestRequest.SerializeToString,
        response_deserializer=test__pb2.TestResponse.FromString,
        )
    self.TestStreamStream = channel.stream_stream(
        '/test.Test/TestStreamStream',
        request_serializer=test__pb2.TestRequest.SerializeToString,
        response_deserializer=test__pb2.TestResponse.FromString,
        )


class TestServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TestStreamSimple(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TestSimpleStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TestSimpleSimple(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TestStreamStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TestStreamSimple': grpc.stream_unary_rpc_method_handler(
          servicer.TestStreamSimple,
          request_deserializer=test__pb2.TestRequest.FromString,
          response_serializer=test__pb2.TestResponse.SerializeToString,
      ),
      'TestSimpleStream': grpc.unary_stream_rpc_method_handler(
          servicer.TestSimpleStream,
          request_deserializer=test__pb2.TestRequest.FromString,
          response_serializer=test__pb2.TestResponse.SerializeToString,
      ),
      'TestSimpleSimple': grpc.unary_unary_rpc_method_handler(
          servicer.TestSimpleSimple,
          request_deserializer=test__pb2.TestRequest.FromString,
          response_serializer=test__pb2.TestResponse.SerializeToString,
      ),
      'TestStreamStream': grpc.stream_stream_rpc_method_handler(
          servicer.TestStreamStream,
          request_deserializer=test__pb2.TestRequest.FromString,
          response_serializer=test__pb2.TestResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test.Test', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
